# Generated by Django 5.2.4 on 2025-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_update_price', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
