# Generated by Django 5.2.4 on 2025-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageModule', '0003_product_deleted_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(null=True),
        ),
    ]
