# Generated by Django 5.2.4 on 2025-07-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageModule', '0004_alter_product_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Relative path to image in toko/globalApp/static/product_photo/', max_length=255, null=True),
        ),
    ]
