# Generated by Django 5.2.4 on 2025-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageModule', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_update_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
