# Generated by Django 5.2.4 on 2025-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storageModule', '0009_alter_product_last_update_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_update_price',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tbproducthistory',
            name='last_update_price',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
