# Generated by Django 5.2.4 on 2025-07-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalApp.tbmenu'),
        ),
        migrations.AlterField(
            model_name='tbmenu',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbmenu',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
